# Generated by Django 3.2.6 on 2021-08-20 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 8, 20, 18, 28, 17, 579809, tzinfo=utc)),
        ),
    ]
